openapi: 3.0.0
info:
  title: Product API
  description: API for managing products
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local server

tags:
  - name: Product
    description: Operations related to Products

paths:
  /api/products:
    get:
      summary: Get all products
      tags:
        - Product
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Create a new product
      tags:
        - Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Product created successfully
        '400':
          description: Bad request

  /api/products/{pid}:
    get:
      summary: Get product by ID
      tags:
        - Product
      parameters:
        - name: pid
          in: path
          required: true
          description: The product ID
          schema:
            type: string
      responses:
        '200':
          description: A single product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
    put:
      summary: Edit a product
      tags:
        - Product
      parameters:
        - name: pid
          in: path
          required: true
          description: The product ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Product updated successfully
        '404':
          description: Product not found
    delete:
      summary: Delete a product
      tags:
        - Product
      parameters:
        - name: pid
          in: path
          required: true
          description: The product ID
          schema:
            type: string
      responses:
        '200':
          description: Product deleted successfully
        '404':
          description: Product not found

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: decimal
        thumbnails:
          type: array
          items:
            type: string
        code:
          type: string
        stock:
          type: integer
        category:
          type: string
        status:
          type: boolean
        owner:
          type: string
          format: objectId
    ProductInput:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: decimal
        thumbnails:
          type: array
          items:
            type: string
        code:
          type: string
        stock:
          type: integer
        category:
          type: string
        status:
          type: boolean
        owner:
          type: string
          format: objectId
